services:

   msnoise:
    image: msnoise:latest
    container_name: msnoise
    hostname: msnoise
      #    build:
      #context: .
      #dockerfile: ./dockerfile/Dockerfile
    ports: 		
     - '6901:6901'
     - '5000:5000' 
     - '1001:22'  
    networks:
     msnoise-network:
      ipv4_address: 172.21.0.2
    volumes:
     - type: bind
       source: /your-sds-archive
       target: /sds-archive
       read_only: true
     - type: bind
       source: ./msnoise-outcome-files
       target: /msnoise-outcome-files   
     - type: bind
       source: ./inventories-for-station-not-on-fdsn
       target: /inventories-for-station-not-on-fdsn
     - type: volume
       source: msnoise_mysql_data
       target: /var/lib/mysql    
     - type: volume
       source: msnoise_project_root
       target: /home/msnoise
   

#---------------------------

volumes:
  msnoise_mysql_data:
    name: msnoise_mysql_data
  msnoise_project_root:
    name: msnoise_project_root  

#---------------------------

networks:
 msnoise-network: 
  name: msnoise-network
  ipam:
   config:
    - subnet: 172.21.0.0/16
